### ISSUE TITLE
when run inference demo, an error occur:  AssertionError: opencd not in {'mmcls': 'mmcls', 'mmdet': 'mmdet', 'mmdet3d': 'mmdet3d', 'mmseg': 'mmsegmentation',

### ISSUE THREAD

**Issue by zcgeqian** [likyoo/open-cd#109]
following the install (https://github.com/likyoo/open-cd/blob/main/docs/install.md) and  inference (https://github.com/likyoo/open-cd/blob/main/docs/inference.md) guide, an error occurred while creating an instance of OpenCDInferencer：
`AssertionError: opencd not in {'mmcls': 'mmcls', 'mmdet': 'mmdet', 'mmdet3d': 'mmdet3d', 'mmseg': 'mmsegmentation', 'mmaction': 'mmaction2', 'mmtrack': 'mmtrack', 'mmpose': 'mmpose', 'mmedit': 'mmedit', 'mmocr': 'mmocr', 'mmgen': 'mmgen', 'mmfewshot': 'mmfewshot', 'mmrazor': 'mmrazor', 'mmflow': 'mmflow', 'mmhuman3d': 'mmhuman3d', 'mmrotate': 'mmrotate', 'mmselfsup': 'mmselfsup', 'mmyolo': 'mmyolo', 'mmpretrain': 'mmpretrain', 'mmagic': 'mmagic'}!,please pass a valid scope.`

environment:
python                  3.9.12
torch                     1.13.0
mmengine                  0.10.4
mmcv                      2.1.0
mmpretrain                1.2.0
mmsegmentation            1.2.2
mmdet                     3.3.0
opencd                    1.1.0        

thanks a lot

**Comment by likyoo** [comment]
Please make sure that opencd is [installed](https://github.com/likyoo/open-cd/blob/main/docs/install.md?plain=1#L34) successfully.

**Comment by zcgeqian** [comment]
![image](https://github.com/likyoo/open-cd/assets/11536889/a1b63043-0a84-42de-b626-d83f096e3120)
and 
`from opencd.apis import OpenCDInferencer `
has been executed correctly.

I have tried the main, v1.1.0 and 1.0.0 branches, but encountered the same issue. I really can't figure out where the problem lies.

**Comment by zcgeqian** [comment]
I rewrote the model parameter of the OpenCDInferencer function to an absolute path to solve this problem.
I will close this issues.
