### ISSUE TITLE
IndexError: index 10995116278530 is out of bounds for dimension 0 with size 1024

### ISSUE THREAD

**Issue by dayn9t** [likyoo/open-cd#13]
cmd line:
```bash
python tools/train.py configs/changer/changer_ex_r18_512x512_40k_levircd.py --work-dir ./changer_r18_levir_workdir --gpu-id 0 --seed 307
```
outputs:
```text
/opt/ias/env/lib/python3.10/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-03-19 00:25:25,391 - mmseg - INFO - Multi-processing start method is `None`
2023-03-19 00:25:25,391 - mmseg - INFO - OpenCV num_threads is `16
2023-03-19 00:25:25,412 - mmseg - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.0, V12.0.76
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.7
MMSegmentation: 0.30.0+d2030d6
------------------------------------------------------------

...

2023-03-19 02:07:41,947 - mmseg - INFO - Saving checkpoint at 16000 iterations
2023-03-19 02:07:42,176 - mmseg - INFO - Exp name: changer_ex_r18_512x512_40k_levircd.py
2023-03-19 02:07:42,176 - mmseg - INFO - Iter [16000/40000]	lr: 3.000e-03, eta: 2:33:22, time: 0.391, data_time: 0.061, memory: 7901, decode.loss_ce: 0.0224, decode.acc_seg: 99.1084, loss: 0.0224
[                                                  ] 0/64, elapsed: 0s, ETA:
[                                  ] 1/64, 4.9 task/s, elapsed: 0s, ETA:    13s
[>                                 ] 2/64, 7.4 task/s, elapsed: 0s, ETA:     8s
[>                                 ] 3/64, 8.8 task/s, elapsed: 0s, ETA:     7s
[>>                                ] 4/64, 9.8 task/s, elapsed: 0s, ETA:     6s
[>>                               ] 5/64, 10.6 task/s, elapsed: 0s, ETA:     6s
[>>>                              ] 6/64, 11.0 task/s, elapsed: 1s, ETA:     5sTraceback (most recent call last):
  File "/mnt/data/jiang/ml/cd/open-cd/tools/train.py", line 243, in <module>
    main()
  File "/mnt/data/jiang/ml/cd/open-cd/tools/train.py", line 232, in main
    train_segmentor(
  File "/mnt/data/jiang/ml/mm/mmsegmentation/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/opt/ias/env/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/ias/env/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/opt/ias/env/lib/python3.10/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/ias/env/lib/python3.10/site-packages/mmcv/runner/hooks/evaluation.py", line 266, in after_train_iter
    self._do_evaluate(runner)
  File "/mnt/data/jiang/ml/mm/mmsegmentation/mmseg/core/evaluation/eval_hooks.py", line 51, in _do_evaluate
    results = single_gpu_test(
  File "/mnt/data/jiang/ml/mm/mmsegmentation/mmseg/apis/test.py", line 128, in single_gpu_test
    result = dataset.pre_eval(result, indices=batch_indices)
  File "/mnt/data/jiang/ml/cd/open-cd/opencd/datasets/custom.py", line 336, in pre_eval
    intersect_and_union(
  File "/mnt/data/jiang/ml/mm/mmsegmentation/mmseg/core/evaluation/metrics.py", line 76, in intersect_and_union
    pred_label = pred_label[mask]
IndexError: index 10995116278530 is out of bounds for dimension 0 with size 1024
```

**Comment by likyoo** [comment]
please provide the config.

**Comment by dayn9t** [comment]
https://github.com/likyoo/open-cd/tree/main/configs/changer/changer_ex_r18_512x512_40k_levircd.py

**Comment by likyoo** [comment]
I mean this file.
![image](https://user-images.githubusercontent.com/44317497/226150542-148b97ae-1064-44b6-a308-2812544236da.png)

**Comment by dayn9t** [comment]
'''python
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='DIEncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='IA_ResNetV1c',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 1, 1),
        strides=(1, 2, 2, 2),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True,
        interaction_cfg=(None, {
            'type': 'SpatialExchange',
            'p': 0.5
        }, {
            'type': 'ChannelExchange',
            'p': 0.5
        }, {
            'type': 'ChannelExchange',
            'p': 0.5
        })),
    decode_head=dict(
        type='Changer',
        in_channels=[64, 128, 256, 512],
        in_index=[0, 1, 2, 3],
        channels=128,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        sampler=dict(type='OHEMPixelSampler', thresh=0.7, min_kept=100000)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'LEVIR_CD_Dataset'
data_root = 'data/LEVIR-CD'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(type='MultiImgLoadAnnotations'),
    dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
    dict(type='MultiImgRandomCrop', crop_size=(512, 512)),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
    dict(type='MultiImgExchangeTime', prob=0.5),
    dict(
        type='MultiImgPhotoMetricDistortion',
        brightness_delta=10,
        contrast_range=(0.8, 1.2),
        saturation_range=(0.8, 1.2),
        hue_delta=10),
    dict(
        type='MultiImgNormalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='MultiImgDefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(
        type='MultiImgMultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='MultiImgResize', keep_ratio=True),
            dict(type='MultiImgRandomFlip'),
            dict(
                type='MultiImgNormalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='MultiImgImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/LEVIR-CD',
        img_dir='train',
        ann_dir='train/label',
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(type='MultiImgLoadAnnotations'),
            dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
            dict(type='MultiImgRandomCrop', crop_size=(512, 512)),
            dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
            dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
            dict(type='MultiImgExchangeTime', prob=0.5),
            dict(
                type='MultiImgPhotoMetricDistortion',
                brightness_delta=10,
                contrast_range=(0.8, 1.2),
                saturation_range=(0.8, 1.2),
                hue_delta=10),
            dict(
                type='MultiImgNormalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='MultiImgDefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/LEVIR-CD',
        img_dir='val',
        ann_dir='val/label',
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(
                type='MultiImgMultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='MultiImgResize', keep_ratio=True),
                    dict(type='MultiImgRandomFlip'),
                    dict(
                        type='MultiImgNormalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='MultiImgImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/LEVIR-CD',
        img_dir='test',
        ann_dir='test/label',
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(
                type='MultiImgMultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='MultiImgResize', keep_ratio=True),
                    dict(type='MultiImgRandomFlip'),
                    dict(
                        type='MultiImgNormalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='MultiImgImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='AdamW', lr=0.005, betas=(0.9, 0.999), weight_decay=0.05)
optimizer_config = dict()
lr_config = dict(
    policy='poly',
    warmup='linear',
    warmup_iters=1500,
    warmup_ratio=1e-06,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=40000)
checkpoint_config = dict(by_epoch=False, interval=4000)
evaluation = dict(
    interval=4000,
    metric=['mFscore', 'mIoU'],
    pre_eval=True,
    save_best='Fscore.changed',
    greater_keys=['Fscore'])
work_dir = './changer_r18_levir_workdir'
gpu_ids = [0]
auto_resume = False

'''

**Comment by dayn9t** [comment]
```python
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='DIEncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='IA_ResNetV1c',
        depth=18,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        dilations=(1, 1, 1, 1),
        strides=(1, 2, 2, 2),
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        norm_eval=False,
        style='pytorch',
        contract_dilation=True,
        interaction_cfg=(None, {
            'type': 'SpatialExchange',
            'p': 0.5
        }, {
            'type': 'ChannelExchange',
            'p': 0.5
        }, {
            'type': 'ChannelExchange',
            'p': 0.5
        })),
    decode_head=dict(
        type='Changer',
        in_channels=[64, 128, 256, 512],
        in_index=[0, 1, 2, 3],
        channels=128,
        dropout_ratio=0.1,
        num_classes=2,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        sampler=dict(type='OHEMPixelSampler', thresh=0.7, min_kept=100000)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'LEVIR_CD_Dataset'
data_root = 'data/LEVIR-CD'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(type='MultiImgLoadAnnotations'),
    dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
    dict(type='MultiImgRandomCrop', crop_size=(512, 512)),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
    dict(type='MultiImgExchangeTime', prob=0.5),
    dict(
        type='MultiImgPhotoMetricDistortion',
        brightness_delta=10,
        contrast_range=(0.8, 1.2),
        saturation_range=(0.8, 1.2),
        hue_delta=10),
    dict(
        type='MultiImgNormalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='MultiImgDefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
test_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(
        type='MultiImgMultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='MultiImgResize', keep_ratio=True),
            dict(type='MultiImgRandomFlip'),
            dict(
                type='MultiImgNormalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='MultiImgImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/LEVIR-CD',
        img_dir='train',
        ann_dir='train/label',
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(type='MultiImgLoadAnnotations'),
            dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
            dict(type='MultiImgRandomCrop', crop_size=(512, 512)),
            dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
            dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
            dict(type='MultiImgExchangeTime', prob=0.5),
            dict(
                type='MultiImgPhotoMetricDistortion',
                brightness_delta=10,
                contrast_range=(0.8, 1.2),
                saturation_range=(0.8, 1.2),
                hue_delta=10),
            dict(
                type='MultiImgNormalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='MultiImgDefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/LEVIR-CD',
        img_dir='val',
        ann_dir='val/label',
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(
                type='MultiImgMultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='MultiImgResize', keep_ratio=True),
                    dict(type='MultiImgRandomFlip'),
                    dict(
                        type='MultiImgNormalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='MultiImgImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='LEVIR_CD_Dataset',
        data_root='data/LEVIR-CD',
        img_dir='test',
        ann_dir='test/label',
        pipeline=[
            dict(type='MultiImgLoadImageFromFile'),
            dict(
                type='MultiImgMultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='MultiImgResize', keep_ratio=True),
                    dict(type='MultiImgRandomFlip'),
                    dict(
                        type='MultiImgNormalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='MultiImgImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(type='AdamW', lr=0.005, betas=(0.9, 0.999), weight_decay=0.05)
optimizer_config = dict()
lr_config = dict(
    policy='poly',
    warmup='linear',
    warmup_iters=1500,
    warmup_ratio=1e-06,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=40000)
checkpoint_config = dict(by_epoch=False, interval=4000)
evaluation = dict(
    interval=4000,
    metric=['mFscore', 'mIoU'],
    pre_eval=True,
    save_best='Fscore.changed',
    greater_keys=['Fscore'])
work_dir = './changer_r18_levir_workdir'
gpu_ids = [0]
auto_resume = False
```

**Comment by likyoo** [comment]
I copy and run your config file and it seems that there is no problem. 

Could you check your data or environment ?

**Comment by aris992-git** [comment]
Could you provide your environment, please?  Such as python, pytorch, torchvision and mmcv-full version, I try to some version of mmcv-full , it is not work.

**Comment by likyoo** [comment]
mmcls                   0.25.0
mmcv-full               1.7.0
mmsegmentation          0.29.1
opencv-python           4.6.0.66
opencv-python-headless  4.7.0.72
pip                     22.3.1
torch                   1.12.1
torchaudio              0.12.1
torchvision             0.13.1

**Comment by dayn9t** [comment]
MMCV: 1.7.1

**Comment by aris992-git** [comment]
Thanks a lot! Code can run.
