### ISSUE TITLE
Dataset configuration files 'multiple values for keyword argument'

### ISSUE THREAD

**Issue by praez-nttd** [likyoo/open-cd#16]
When trying to use the base configuration for testing the DSIFN dataset I get the following error msg:

TypeError: DSIFN_Dataset: opencd.datasets.custom.CDDataset.__init__() got multiple values for keyword argument 'seg_map_suffix'

This is due the DSIFN dataset having a .tiff extension on its test annotations instead of .png which would be the default. The configuration is the same as the one used for training, which works totally fine.

This behavior can be appreciated when trying to test with both changerex and changeformer architectures, so I understand the issue lays in the dataset.

Is there any way of going around this error?.

**Comment by likyoo** [comment]
I fixed this bug [here](https://github.com/likyoo/open-cd/commit/efbbe03f056f6cea9359ba27b78587b141280e07).

**Comment by praez-nttd** [comment]
Thank you for solving it so quickly
