### ISSUE TITLE
exhanger window

### ISSUE THREAD

**Issue by linyiyuan11** [likyoo/open-cd#17]
A worthwhile consideration is whether small exchange patch in spatial exchange would disrupt the original spatial structure. We therefore tried using different window sizes in spatial exchange, from 1 × 1 to 8 × 8, as listed in the Tab. 6. We find that the window size is a robust hyper-parameter and that a more complete original spatial structure does not result in a performance gain.

请问您这里的exhanger window是什么意思呢，代码似乎没这方面体现。

**Comment by likyoo** [comment]
你好，指的是空间交换窗口的大小，根据实验结果，为了代码更简洁一点，所以删掉了这部分。
