### ISSUE TITLE
作者您好，我在运行最新版本代码的训练命令时，代码出现如下报错，想请问作者解决方法？十分感谢

### ISSUE THREAD

**Issue by WeiCL7777** [likyoo/open-cd#20]
04/22 04:30:00 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
04/22 04:30:00 - mmengine - WARNING - Failed to search registry with scope "opencd" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "opencd" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/remote-home/clwei/WCL/open-cd-1.x/tools/train.py", line 105, in <module>
    main()
  File "/remote-home/clwei/WCL/open-cd-1.x/tools/train.py", line 94, in main
    runner = Runner.from_cfg(cfg)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 393, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 780, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'CDLocalVisualizer is not in the visualizer registry. Please check whether the value of `CDLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by likyoo** [comment]
您好，我刚刚改了一下[registry.py](https://github.com/likyoo/open-cd/blob/1.x/opencd/registry.py)的内容。  
使用v1.0.0时，参考安装依赖：
```
# Install OpenMMLab Toolkits as Python packages
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0"
mim install "mmpretrain>=1.0.0rc6"
pip install "mmsegmentation>=1.0.0"
pip install "mmdet>=3.0.0"
```
```
git clone https://github.com/likyoo/open-cd.git
cd open-cd
pip install -v -e .
```
根据您的问题，请确定一下是否安装了opencd v1.0.0

**Comment by WeiCL7777** [comment]
> 您好，我刚刚改了一下[registry.py](https://github.com/likyoo/open-cd/blob/1.x/opencd/registry.py)的内容。 使用v1.0.0时，参考安装依赖：
> 
> ```
> # Install OpenMMLab Toolkits as Python packages
> pip install -U openmim
> mim install mmengine
> mim install "mmcv>=2.0.0"
> mim install "mmpretrain>=1.0.0rc6"
> pip install "mmsegmentation>=1.0.0"
> pip install "mmdet>=3.0.0"
> ```
> 
> ```
> git clone https://github.com/likyoo/open-cd.git
> cd open-cd
> pip install -v -e .
> ```
> 
> 根据您的问题，请确定一下是否安装了opencd v1.0.0

谢谢作者的解答，训练问题已解决，跑通了changer的训练过程，也生成了一系列的.pth模型文件。之后在运行测试命令时，还是有如下报错，希望作者能帮忙解决，谢谢。
04/22 09:17:50 - mmengine - WARNING - The prefix is not set in metric class IoUMetric.
Loads checkpoint by local backend from path: changer_r18_levir_workdir/latest.pth
Traceback (most recent call last):
  File "/remote-home/clwei/WCL/CD/open-cd-1.x/tools/test.py", line 114, in <module>
    main()
  File "/remote-home/clwei/WCL/CD/open-cd-1.x/tools/test.py", line 110, in main
    runner.test()
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1750, in test
    self.load_or_resume()
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1643, in load_or_resume
    self.load_checkpoint(self._load_from)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 2051, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location=map_location)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 518, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 300, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 316, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: changer_r18_levir_workdir/latest.pth can not be found.

**Comment by likyoo** [comment]
需要将changer_r18_levir_workdir/latest.pth换成你的checkpoint路径

**Comment by WeiCL7777** [comment]
> 


> 需要将changer_r18_levir_workdir/latest.pth换成你的checkpoint路径

好的好的，已解决，谢谢作者指导。

**Comment by timacro** [comment]
我也遇到了同样的警告：
```
quantization_config convert to <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>
12/14 16:17:52 - mmengine - WARNING - Failed to search registry with scope "mmengine" in the "builder" registry tree. As a workaround, the current "builder" registry in "xtuner" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmengine" is a correct scope, or whether the registry is initialized.
```

按照前面的指导安装后，警告仍然没有消除，但是训练可以正常进行。请问这个警告对结果有影响吗？

> > 您好，我刚刚改了一下[registry.py](https://github.com/likyoo/open-cd/blob/1.x/opencd/registry.py)的内容。 使用v1.0.0时，参考安装依赖：
> > ```
> > # Install OpenMMLab Toolkits as Python packages
> > pip install -U openmim
> > mim install mmengine
> > mim install "mmcv>=2.0.0"
> > mim install "mmpretrain>=1.0.0rc6"
> > pip install "mmsegmentation>=1.0.0"
> > pip install "mmdet>=3.0.0"
> > ```
> >   
> > ```
> > git clone https://github.com/likyoo/open-cd.git
> > cd open-cd
> > pip install -v -e .
> > ```

**Comment by timacro** [comment]
我也遇到了同样的警告：
```
quantization_config convert to <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>
12/14 16:17:52 - mmengine - WARNING - Failed to search registry with scope "mmengine" in the "builder" registry tree. As a workaround, the current "builder" registry in "xtuner" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmengine" is a correct scope, or whether the registry is initialized.
```

按照前面的指导安装后，警告仍然没有消除，但是训练可以正常进行。请问这个警告对结果有影响吗？

> > 您好，我刚刚改了一下[registry.py](https://github.com/likyoo/open-cd/blob/1.x/opencd/registry.py)的内容。 使用v1.0.0时，参考安装依赖：
> > ```
> > # Install OpenMMLab Toolkits as Python packages
> > pip install -U openmim
> > mim install mmengine
> > mim install "mmcv>=2.0.0"
> > mim install "mmpretrain>=1.0.0rc6"
> > pip install "mmsegmentation>=1.0.0"
> > pip install "mmdet>=3.0.0"
> > ```
> >   
> > ```
> > git clone https://github.com/likyoo/open-cd.git
> > cd open-cd
> > pip install -v -e .
> > ```

**Comment by LegionHXF** [comment]
> > 您好，我刚刚改了一下[registry.py](https://github.com/likyoo/open-cd/blob/1.x/opencd/registry.py)的内容。 使用v1.0.0时，参考安装依赖：
> > ```
> > # Install OpenMMLab Toolkits as Python packages
> > pip install -U openmim
> > mim install mmengine
> > mim install "mmcv>=2.0.0"
> > mim install "mmpretrain>=1.0.0rc6"
> > pip install "mmsegmentation>=1.0.0"
> > pip install "mmdet>=3.0.0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > git clone https://github.com/likyoo/open-cd.git
> > cd open-cd
> > pip install -v -e .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 根据您的问题，请确定一下是否安装了opencd v1.0.0
> 
> 谢谢作者的解答，训练问题已解决，跑通了changer的训练过程，也生成了一系列的.pth模型文件。之后在运行测试命令时，还是有如下报错，希望作者能帮忙解决，谢谢。 04/22 09:17:50 - mmengine - WARNING - The prefix is not set in metric class IoUMetric. Loads checkpoint by local backend from path: changer_r18_levir_workdir/latest.pth Traceback (most recent call last): File "/remote-home/clwei/WCL/CD/open-cd-1.x/tools/test.py", line 114, in main() File "/remote-home/clwei/WCL/CD/open-cd-1.x/tools/test.py", line 110, in main runner.test() File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1750, in test self.load_or_resume() File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1643, in load_or_resume self.load_checkpoint(self._load_from) File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/runner.py", line 2051, in load_checkpoint checkpoint = _load_checkpoint(filename, map_location=map_location) File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 518, in _load_checkpoint return CheckpointLoader.load_checkpoint(filename, map_location, logger) File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 300, in load_checkpoint return checkpoint_loader(filename, map_location) File "/remote-home/clwei/anaconda3/envs/py39/lib/python3.9/site-packages/mmengine/runner/checkpoint.py", line 316, in load_from_local raise FileNotFoundError(f'{filename} can not be found.') FileNotFoundError: changer_r18_levir_workdir/latest.pth can not be found.

你好，我下了open-cdV1.0.0版本而且环境都符合，可还是报此错误，请问该如何解决？
下面是我的版本 ， 
mmcv                      2.1.0                     <pip>
mmdet                     3.2.0                     <pip>
mmengine                  0.10.1                    <pip>
mmpretrain                1.1.1                     <pip>
mmsegmentation            1.2.2
opencd                    1.0.0                     <pip>
下面是建议的版本
mim install mmengine
mim install "mmcv>=2.0.0"
mim install "mmpretrain>=1.0.0rc6"
pip install "mmsegmentation>=1.0.0"
pip install "mmdet>=3.0.0"
（目前：在复现BAN的代码！）
