### ISSUE TITLE
请问怎么利用cutmix和mixup

### ISSUE THREAD

**Issue by xiaoyelulu** [likyoo/open-cd#22]
请问如何在模型的data_preprocessor利用cutmix或者mixup，对应参数应该如何填写？dict(type='Cutmix')这样写好像会报错
![屏幕截图 2023-04-25 180118](https://user-images.githubusercontent.com/74903786/234243491-5d277e4e-651f-483e-891e-5f1035e23e08.png)

**Comment by likyoo** [comment]
你好，目前还未支持CutMix、Mixup，欢迎PR

**Comment by likyoo** [comment]
可以尝试以下mmcls提供的CutMix、Mixup。参考[resnet50_cutmix](https://github.com/open-mmlab/mmpretrain/blob/main/configs/_base_/models/resnet50_cutmix.py)和[resnet50_mixup](https://github.com/open-mmlab/mmpretrain/blob/main/configs/_base_/models/resnet50_mixup.py)。
