### ISSUE TITLE
CDD dataset and resuming training

### ISSUE THREAD

**Issue by AgustinNormand** [likyoo/open-cd#23]
Hello, I am starting a research project related to change detection in Argentina.

I would appreciate if you answer these two questions.

Do you support CDD dataset?
Because I want to test the efficiency and effectiveness of OpenCD against this model: https://github.com/qaz670756/LSNet

Do you support resuming training from a checkpoint?
Because I want to carry out the training using google colab and it is a quite interrupted environment, for which I need to be able to resume the training through the persistence of partial states, epochs or checkpoints.

Thanks since now!

**Comment by likyoo** [comment]
1. Yes, CDD dataset is re-named to SVCD (season varying) in OpenCD.
2. Yes! If you use v0.x version, you can use `--resume-from` in [train.py](https://github.com/likyoo/open-cd/blob/main/tools/train.py); and if you use v1.x version, use `--resume` when run the new [train.py](https://github.com/likyoo/open-cd/blob/1.x/tools/train.py) file.

**Comment by AgustinNormand** [comment]
Hello!

Thank you for your answers!

I have one last question, which is quite specific, in case you don't know how to answer it, there is no problem, you already helped me a lot with the previous answers!

In Argentina, access to GPU is very expensive, so an important aspect of our research work is the efficiency of the neural network used. That's why our first attempts were with [LSNet](https://github.com/qaz670756/LSNet) since it poses a very similar F1 score to your previous model [Siam-NestedUNet](https://github.com/likyoo/Siam-NestedUNet) but a song from much lower GFLOPS:
![image](https://user-images.githubusercontent.com/48933518/234579721-870d5161-b335-4be4-a1b7-98bab8c32654.png)
(Image taken from the LSNet paper, look at the point labeled "our")

Can you tell me if OpenCD improves Siam-NestedUNet in terms of GFLOPS?

Because if so, and if it is closer to LSNet, I can't find any reason why OpenCD should not be the main quote of the research article, because it is the neural network model where we are going to work.

Thanks for taking the time to answer me.

Greetings.

**Comment by likyoo** [comment]
For GFLOPs, there is no improvement. OpenCD provides better data processing and overall pipeline, but no changes to the model.

BTW, TinyCD and TinyCDv2 in OpenCD may be useful for you.

PS: The TinyCDv2 paper is not yet available.

**Comment by AgustinNormand** [comment]
I'm going to look at those references that you tell me.

Thanks a lot!

Greetings!

**Comment by AgustinNormand** [comment]
> BTW, TinyCD and TinyCDv2 in OpenCD may be useful for you.

With "BTW" here do you mean BiT? The model of the paper "[Remote Sensing Image Change Detection with Transformers](https://arxiv.org/abs/2103.00208)" and this [bit_r18_256x256_40k_levircd.py](https://github.com/likyoo/open-cd/blob/1.x/configs/bit/bit_r18_256x256_40k_levircd.py) config file?
