### ISSUE TITLE
Bug in TinyCD_V2 and GPU usage question

### ISSUE THREAD

**Issue by AgustinNormand** [likyoo/open-cd#25]
Hello!

I have a possible bug, and a question to ask.

Starting with the bug, I think tinycd_v2 is not working.
I am in a Google Colab environment, using OpenCD 1.x, the steps I am following are:
* Install dependencies
* Clone the repository
* I download the LEVIR-CD dataset
* I run the training
```
!python3 tools/train.py configs/tinycd_v2/tinycd_v2_s_256x256_40k_levircd.py --work-dir ./tinycd_v2_s_levir_workdir
```
or
```
!python3 tools/train.py configs/tinycd_v2/tinycd_v2_b_256x256_40k_levircd.py  --work-dir ./tinycd_v2_b_levir_workdir
```
or
```
!python3 tools/train.py configs/tinycd_v2/tinycd_v2_l_256x256_40k_levircd.py  --work-dir ./tinycd_v2_l_levir_workdir
```

And in all three cases I get the same errors:
```
KeyError: 'Cannot find None in registry under scope name opencd'
...
KeyError: "class `TinyNet` in opencd/models/backbones/tinynet.py: 'Cannot find None in registry under scope name opencd'"
...
KeyError: 'class `DIEncoderDecoder` in opencd/models/change_detectors/dual_input_encoder_decoder.py: "class `TinyNet` in opencd/models/backbones/tinynet.py: \'Cannot find None in registry under scope name opencd\'"'
```

Complete output files:
[error_tinycd_v2_b_256x256_40k_levircd.txt](https://github.com/likyoo/open-cd/files/11343810/error_tinycd_v2_b_256x256_40k_levircd.txt)
[error_tinycd_v2_l_256x256_40k_levircd.txt](https://github.com/likyoo/open-cd/files/11343811/error_tinycd_v2_l_256x256_40k_levircd.txt)
[error_tinycd_v2_s_256x256_40k_levircd.txt](https://github.com/likyoo/open-cd/files/11343812/error_tinycd_v2_s_256x256_40k_levircd.txt)

It should be noted that if I change the training line to any of the following configurations, which also use the LEVIR-CD dataset, it works perfectly, and the training begins:
```
!python3 tools/train.py configs/tinycd/tinycd_256x256_40k_levircd.py --work-dir ./tinycd_v1_levir_workdir
!python3 tools/train.py configs/bit/bit_r18_256x256_40k_levircd.py --work-dir ./bit_levir_workdir
!python tools/train.py configs/changer/changer_ex_r18_512x512_40k_levircd.py --work-dir ./changer_r18_levir_workdir 
!python tools/train.py configs/snunet/snunet_c16_256x256_40k_levircd.py --work-dir ./snunet_c16_levir_workdir
```

And this gives me the opportunity to ask the question that I wanted to ask. During the training of these last configurations, they only use 5GB of the 15GB that I have available from the CPU in Colab. Is it possible to modify some parameter so that they take advantage of 100% of the board?

Thank you very much

**Comment by likyoo** [comment]
1. I fixed it [here](https://github.com/likyoo/open-cd/commit/3a194aa8e4a9cba7c09da1a449863242e23327f5)

**Comment by AgustinNormand** [comment]
Awesome! Thank you very much for the answers and correct it so quickly!
