### ISSUE TITLE
How to obtain the mmsegmentation-pretrained backbone checkpoint?

### ISSUE THREAD

**Issue by dou3516** [likyoo/open-cd#26]
When add a new config for backbone not exists in current configs, e.g. mit-b2, I can't find the checkpoint url like (from changer_ex_mit-b1_512x512_40k_levircd.py) :
`checkpoint = 'https://download.openmmlab.com/mmsegmentation/v0.5/pretrain/segformer/mit_b1_20220624-02e5a6a1.pth'  `

How to obtain the url of mmsegmentation-pretrained backbone checkpoint?

**Comment by likyoo** [comment]
you can find them in segformer configs in [mmseg 0.x](https://github.com/open-mmlab/mmsegmentation/tree/0.x)

**Comment by dou3516** [comment]
> you can find them in segformer configs in [mmseg 0.x](https://github.com/open-mmlab/mmsegmentation/tree/0.x)

I got it.
