### ISSUE TITLE
[Question] Is the metric calculated based on the validation set or on the test set?

### ISSUE THREAD

**Issue by Bobholamovic** [likyoo/open-cd#3]
Hi, *Changer* is an awesome work with a novel idea, and the experiments are elaborative. I found it really helpful to me. 

Observed from the [log](https://drive.google.com/file/d/18qcXeyC6rq-l04vS5I5n3VAhh0HsCxFF/view?usp=sharing), it seems that the F1-score of 92.33 reported [here](https://github.com/likyoo/open-cd/tree/main/configs/changer) (and also in the paper) was calculated with the validation data. I wonder if it is the expected experimental setup and desired behavior, given that the F1-score calculated on the validation set is usually higher than that calculated on the test set, and most paper have reported the test set scores.

**Update**: I have computed the F1-score on the test set of [this model](https://drive.google.com/file/d/128FVQL-93oN5lUMGuqDcmPU-80RiXBhn/view) using the `tools/test.py` script introduced in README. The F1-score of change class was about 1% lower than 92.33%.

**Comment by likyoo** [comment]
Hi @Bobholamovic , thanks for your attention! and open the first issue of opencd !😃 

In fact, the scores reported in the log files are all on the test data.
I have recomputed the F1-score on the validation data and the test data and the results are 92.32 and 92.33 respectively. 
the testing command is: 
```
python tools/test.py configs/changer/changer_s101_512x512_40k_levircd.py weights/ChangerEx_s101-512x512_40k_levircd_20220710-082722.pth --eval mFscore
```

I am also confused about the difference in our test results, and I think we can discuss this further.

**Comment by Bobholamovic** [comment]
Sorry it looks like that I might have mis-read the recall as the F1-score. My bad! I'm closing this issue. Thank you for the great paper (and the clean code) and the kind replies.
