### ISSUE TITLE
 FC_EF 

### ISSUE THREAD

**Issue by kk-kaii** [likyoo/open-cd#40]
![image](https://github.com/likyoo/open-cd/assets/105615283/5fb68aeb-2dcd-45c4-b6b8-e60052cdd1ff)
Hello, why is the result accuracy so low when I use the FC_EF network to run the levircd dataset? Do you still need any operation codes

**Comment by likyoo** [comment]
Please provide the detailed config file.

**Comment by kk-kaii** [comment]
> Please provide the detailed config file.

你好 我是直接使用tools/train.py configs/fcsn/fc_ef_256x256_40k_levircd.py 来运行的 然后其他的原始代码都是下载您提供的 没有变

**Comment by likyoo** [comment]
数据是直接使用的原始的levir-cd数据集吗（不需要提前切分）？

**Comment by kk-kaii** [comment]
> 数据是直接使用的原始的levir-cd数据集吗（不需要提前切分）？

数据集是按照要求分了的 没问题 都切分成了256×256的

**Comment by likyoo** [comment]
按照提供的配置文件，不需要提前切分成256×256的patch。
您使用原始数据试一下。

**Comment by kk-kaii** [comment]
> 按照提供的配置文件，不需要提前切分成256×256的patch。 您使用原始数据试一下。

哦哦 是不需要切分吗 好滴我试试

**Comment by kk-kaii** [comment]
> 按照提供的配置文件，不需要提前切分成256×256的patch。 您使用原始数据试一下。

![image](https://github.com/likyoo/open-cd/assets/105615283/089da2e4-9a70-41d8-8904-7d67f954fd47)
如果要切成256×256的 是不是要把这改成256×256啊

**Comment by likyoo** [comment]
不需要，[fc_ef_256x256_40k_levircd.py](https://github.com/likyoo/open-cd/blob/main/configs/fcsn/fc_ef_256x256_40k_levircd.py)中没有继承那个配置文件。

**Comment by kk-kaii** [comment]
> 不需要，[fc_ef_256x256_40k_levircd.py](https://github.com/likyoo/open-cd/blob/main/configs/fcsn/fc_ef_256x256_40k_levircd.py)中没有继承那个配置文件。

好滴 谢谢 我还有一个问题 我后面需要在自己做的数据集上跑对比实验 自己的数据集可以 导入open-cd里面吗 但是数据的处理的程序可以用您提供的数据处理程序吗？

**Comment by kk-kaii** [comment]
因为我看原始的mmseg可以导入自己的数据集，然后稍微改一下参数就能使用

**Comment by likyoo** [comment]
与mmseg使用方法基本一致
