### ISSUE TITLE
无法复现文章精度

### ISSUE THREAD

**Issue by everglow1024** [likyoo/open-cd#44]
作者您好，我按照您的参数设置，尝试复现changer_ex_mit-b0_512x512_40k_levircd.py与changer_ex_r18_512x512_40k_levircd.py 的精度，距离文章精度相差0.50与0.7左右，请问我该从哪里来解决问题呢？

**Comment by likyoo** [comment]
感谢您的使用，changer_ex_mit-b0_512x512_40k_levircd的精度浮动是比较大的，但changer_ex_r18_512x512_40k_levircd在我的实验中相对较为稳定，不知道您是否修改了部分参数，您可以将完整的配置文件展示一下。

**Comment by everglow1024** [comment]
您好，这是我的配置文件：
_base_ = [
    '../_base_/models/changer_r18.py', 
    '../common/standard_512x512_40k_levircd.py']

crop_size = (512, 512)
model = dict(
    backbone=dict(
        interaction_cfg=(
            None,
            dict(type='SpatialExchange', p=1/2),
            dict(type='ChannelExchange', p=1/2),
            dict(type='ChannelExchange', p=1/2))
    ),
    decode_head=dict(
        num_classes=2,
        sampler=dict(type='mmseg.OHEMPixelSampler', thresh=0.7, min_kept=100000)),
        # test_cfg=dict(mode='slide', crop_size=crop_size, stride=(crop_size[0]//2, crop_size[1]//2)),
    )

train_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(type='MultiImgLoadAnnotations'),
    dict(type='MultiImgRandomRotFlip', rotate_prob=0.5, flip_prob=0.5, degree=(-20, 20)),
    dict(type='MultiImgRandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='MultiImgExchangeTime', prob=0.5),
    dict(
        type='MultiImgPhotoMetricDistortion',
        brightness_delta=10,
        contrast_range=(0.8, 1.2),
        saturation_range=(0.8, 1.2),
        hue_delta=10),
    dict(type='MultiImgPackSegInputs')
]

train_dataloader = dict(
    dataset=dict(pipeline=train_pipeline))

# optimizer
optimizer=dict(
    type='AdamW', lr=0.005, betas=(0.9, 0.999), weight_decay=0.05)
optim_wrapper = dict(
    _delete_=True,
    type='OptimWrapper',
    optimizer=optimizer)

# compile = True # use PyTorch 2.x

**Comment by everglow1024** [comment]
> 您所使用的数据是1024*1024的图像吗？若是的话，烦请再重复一次实验。另外，你指的精度是F1-Score吗？

作者您好，感谢您昨天提供的帮助，我昨晚重新试了一下changer_ex_r18_512x512_40k_levircd的结果，十分接近您文章里的精度。我还想请教一下，您能提供在进行changer_ex_mit-b0_512x512_40k_levircd实验时，使用的pytorch和cuda的版本号吗，因为我想尽可能地在与您相同的环境下再尝试一次，十分感谢。

**Comment by likyoo** [comment]
抱歉，由于我已经毕业，没有权限再登陆之前的服务器。即使是pytorch和cuda版本一致，设备型号不同也可能会导致不确定的结果。您可以使用config页面所提供的训练好的模型。

**Comment by everglow1024** [comment]
> 抱歉，由于我已经毕业，没有权限再登陆之前的服务器。即使是pytorch和cuda版本一致，设备型号不同也可能会导致不确定的结果。您可以使用config页面所提供的训练好的模型。

好吧，感谢您的回复和建议。
