### ISSUE TITLE
Running Inference Using Trained Model

### ISSUE THREAD

**Issue by the5solae** [likyoo/open-cd#46]
Hi all,

So I've trained a couple of models and I was wondering how I can run inference on a different data (that don't have labels) without using the tools/test.py script. An example would be really helpful. 

Thank you.

**Comment by rsorbello** [comment]
The solution to this question would be greatly appreciated.  If I have a dataset formatted as follows:

|── dataset
│   |── A
│   |── B

Where A, and B are the folders containing bitemporal images, can I just run one of your pretrained models (say from https://github.com/likyoo/open-cd/tree/main/configs/changer) through it? Thank you very much in advance.

**Comment by the5solae** [comment]
@likyoo I tried implementing this solution https://github.com/likyoo/open-cd/issues/8 with the new mmseg apis, but I keep running into errors. I was wondering if you could assist with the new MMSeg APIs. Downgrading breaks MMCV, MMSEG library breaks OPEN-CD

**Comment by likyoo** [comment]
Hi~, Open-CD supports inference api now 😃 ! see [here](https://github.com/likyoo/open-cd/blob/main/docs/inference.md)

**Comment by the5solae** [comment]
Hi @likyoo thank you for adding the inference api. Works fine with passing the images as paths but throws an error when I pass the image as arrays. Error attached below: 

`Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  
IndexError                                Traceback (most recent call last)
----> 1 result = inferencer([[arr1,arr2]], show=False, out_dir='results')
[/content/open-cd/opencd/datasets/transforms/loading.py](https://localhost:8080/#) in transform(self, results)
    390         results['img_path'] = None
    391         results['img'] = imgs
--> 392         results['img_shape'] = imgs[0].shape[:2]
    393         results['ori_shape'] = imgs[0].shape[:2]
    394         return results
IndexError: list index out of range`

I'll close this issue as using image paths works well in my case. Thank you again.
