### ISSUE TITLE
why???

### ISSUE THREAD

**Issue by er2q** [likyoo/open-cd#5]
![image](https://user-images.githubusercontent.com/48881536/195480862-f34c00dc-88a1-4201-ae66-26ecc9c813a4.png)

**Comment by likyoo** [comment]
I am checking it .....

**Comment by likyoo** [comment]
emmmm..... it seems you have 4000 images to test? but there are 1000 images in s2looking test set...
I re-run the test code with the following results:
![image](https://user-images.githubusercontent.com/44317497/195485924-90811a47-cc38-4ad1-b863-2f7e8c087f60.png)
