### ISSUE TITLE
train问题

### ISSUE THREAD

**Issue by linyiyuan11** [likyoo/open-cd#6]
作者你好，请问你这个模型训练集和测试集是放在一起训练的吗，为什么我用你的代码跑出来的结果和你差距很大。
![D9_))8TA51CY0C`N}L$L0M9](https://user-images.githubusercontent.com/90677655/201518324-ecf02d1e-31d9-4ec2-8fbd-7ff2f661b51b.png)

**Comment by likyoo** [comment]
麻烦分享下你的配置文件，说明一下数据集和其他基本信息

**Comment by likyoo** [comment]
如果实在看不懂逻辑，可以去学习一下open-mmlab相关repo的文档、教程等

**Comment by linyiyuan11** [comment]
使用的是s2looking数据集。
配置文件：
_base_ = [
    '../_base_/models/changer_r18.py', '../_base_/datasets/s2looking.py', 
    '../_base_/default_runtime.py', '../_base_/schedules/schedule_20k.py'
]

crop_size = (512, 512)
model = dict(
    decode_head=dict(
        num_classes=2,
        sampler=dict(type='OHEMPixelSampler', thresh=0.7, min_kept=100000)),
        # test_cfg=dict(mode='slide', crop_size=crop_size, stride=(crop_size[0]//2, crop_size[1]//2)),
    )

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(type='MultiImgLoadAnnotations'),
    dict(type='MultiImgRandomRotate', prob=0.5, degree=180),
    dict(type='MultiImgRandomCrop', crop_size=crop_size),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='horizontal'),
    dict(type='MultiImgRandomFlip', prob=0.5, direction='vertical'),
    dict(type='MultiImgExchangeTime', prob=0.5),
    dict(
        type='MultiImgPhotoMetricDistortion',
        brightness_delta=10,
        contrast_range=(0.8, 1.2),
        saturation_range=(0.8, 1.2),
        hue_delta=10),
    dict(type='MultiImgNormalize', **img_norm_cfg),
    dict(type='MultiImgDefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='MultiImgLoadImageFromFile'),
    dict(
        type='MultiImgMultiScaleFlipAug',
        img_scale=(1024, 1024),
        # img_ratios=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
        flip=False,
        transforms=[
            dict(type='MultiImgResize', keep_ratio=True),
            dict(type='MultiImgRandomFlip'),
            dict(type='MultiImgNormalize', **img_norm_cfg),
            dict(type='MultiImgImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    train=dict(
        img_dir='/media/qq/0CBE052B0CBE052B/dataset/lyy/s2looking/S2Looking/S2Looking/train',
        ann_dir='/media/qq/0CBE052B0CBE052B/dataset/lyy/s2looking/S2Looking/S2Looking/train/label',
        pipeline=train_pipeline),
    val=dict(
        img_dir='/media/qq/0CBE052B0CBE052B/dataset/lyy/s2looking/S2Looking/S2Looking/val',
        ann_dir='/media/qq/0CBE052B0CBE052B/dataset/lyy/s2looking/S2Looking/S2Looking/val/label',
        pipeline=test_pipeline),
    test=dict(
        img_dir='/media/qq/0CBE052B0CBE052B/dataset/lyy/s2looking/S2Looking/S2Looking/test',
        ann_dir='/media/qq/0CBE052B0CBE052B/dataset/lyy/s2looking/S2Looking/S2Looking/test/label',
        pipeline=test_pipeline))

log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
    ])

# optimizer
optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.001,
    betas=(0.9, 0.999),
    weight_decay=0.05)

lr_config = dict(
    _delete_=True,
    policy='poly',
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=1e-6,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)

runner = dict(type='IterBasedRunner', max_iters=80000)
checkpoint_config = dict(by_epoch=False, interval=8000)
evaluation = dict(interval=8000, metric=['mFscore', 'mIoU'], pre_eval=True, save_best='Fscore.changed', greater_keys=['Fscore'])

**Comment by linyiyuan11** [comment]
我的训练和测试过程是：按照readme中的训练命令进行训练，后挑选F1_best.pth权重，在tool/test.py中进行测试

**Comment by likyoo** [comment]
可以把你训练之后的work-dir中的那个配置文件和log文件分享一下吗

**Comment by linyiyuan11** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "likyoo/open-cd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月13日(星期天) 晚上7:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [likyoo/open-cd] train问题 (Issue #6)





 
可以把你训练之后的work-dir中的那个配置文件和log文件分享一下吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

temp.zip (120.62M, 2022年12月13日 19:22 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=5b303133df3a4ecde2e6ad5a42310a1a5500060a55530f534b080051521c0c0153541c0a5154001851000106020108020003520464393841035d411d1e5848355b&code=f013d185

**Comment by linyiyuan11** [comment]
已通过邮箱分享

**Comment by likyoo** [comment]
已收到。
您可以试一下把samples_per_gpu设置为8。另外，建议使用最后一次保存的模型测试。

**Comment by linyiyuan11** [comment]
感谢您的回复，我已试过last.bt，但结果和上面差不多

**Comment by likyoo** [comment]
客气了，目前的lr等超参数是在batch size=8下调的，您如果使用单卡的话，可以将samples_per_gpu设置为8

**Comment by linyiyuan11** [comment]
非常感谢您的热心回复，我修改samples_per_gpu后再继续尝试一下。
