### ISSUE TITLE
大佬，可以提供一个导出onnx的demo吗

### ISSUE THREAD

**Issue by yangshenchang** [likyoo/open-cd#7]

**Comment by likyoo** [comment]
可以参考下https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/useful_tools.md

**Comment by yangshenchang** [comment]
> 可以参考下https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/useful_tools.md

好的，感谢大佬
