### ISSUE TITLE
Questions about api

### ISSUE THREAD

**Issue by boxbox-0427** [likyoo/open-cd#8]
Thanks for your work!

I am wondering are there any apis like `mmseg.apis` such as below
```
from mmseg.apis import inference_segmentor, init_segmentor
import mmcv

config_file = 'pspnet_r50-d8_512x1024_40k_cityscapes.py'
checkpoint_file = 'pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth'

# build the model from a config file and a checkpoint file
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')

# test a single image and show the results
img = 'test.jpg'  # or img = mmcv.imread(img), which will only load it once
result = inference_segmentor(model, img)
# visualize the results in a new window
model.show_result(img, result, show=True)
# or save the visualization results to image files
# you can change the opacity of the painted segmentation map in (0, 1].
model.show_result(img, result, out_file='result.jpg', opacity=0.5)

# test a video and show the results
video = mmcv.VideoReader('video.mp4')
for frame in video:
   result = inference_segmentor(model, frame)
   model.show_result(frame, result, wait_time=1)
```

so that I can use `inference_detector` to detector the change between two images?

It will be more convenient with both `api` and `command line`, I think.

**Comment by likyoo** [comment]
Sorry for the delay in replying to you, you can try the following code.
```
import mmcv
import torch
from mmcv.parallel import collate, scatter

from mmseg.apis import init_segmentor
from mmseg.datasets.pipelines import Compose
from opencd.models import *


class LoadImage:
    """A simple pipeline to load image."""

    def __call__(self, results):
        """Call function to load images into results.

        Args:
            results (dict): A result dict contains the file name
                of the image to be read.

        Returns:
            dict: ``results`` will be returned containing loaded image.
        """

        results['filename'] = None
        results['ori_filename'] = None
        results['img'] = img
        results['img_shape'] = img[0].shape
        results['ori_shape'] = img[0].shape
        return results


def inference_segmentor(model, imgs):
    """Inference image(s) with the segmentor.

    Args:
        model (nn.Module): The loaded segmentor.
        imgs (str/ndarray or list[str/ndarray]): Either image files or loaded
            images.

    Returns:
        (list[Tensor]): The segmentation result.
    """
    cfg = model.cfg
    device = next(model.parameters()).device  # model device
    # build the data pipeline
    test_pipeline = [LoadImage()] + cfg.data.test.pipeline[1:]
    test_pipeline = Compose(test_pipeline)
    # prepare data
    data = []
    imgs = imgs if isinstance(imgs[0], list) else [imgs]
    for img in imgs:
        img_data = dict(img=img)
        img_data = test_pipeline(img_data)
        data.append(img_data)
    data = collate(data, samples_per_gpu=len(imgs))
    if next(model.parameters()).is_cuda:
        # scatter to specified GPU
        data = scatter(data, [device])[0]
    else:
        data['img_metas'] = [i.data[0] for i in data['img_metas']]

    # forward the model
    with torch.no_grad():
        result = model(return_loss=False, rescale=True, **data)
    return result


config_file = 'configs/changer/changer_ex_r18_512x512_40k_levircd.py'
checkpoint_file = 'weights/ChangerEx_r18-512x512_40k_levircd_20221223_120511.pth'

# build the model from a config file and a checkpoint file
model = init_segmentor(config_file, checkpoint_file, device='cuda:0')

# test a single image and show the results
img1 = mmcv.imread('data/LEVIR-CD/test/A/test_1.png')
img2 = mmcv.imread('data/LEVIR-CD/test/B/test_1.png')
img = [img1, img2]

result = inference_segmentor(model, img)

```

**Comment by boxbox-0427** [comment]
> Sorry for the delay in replying to you, you can try the following code.
> 
> ```
> import mmcv
> import torch
> from mmcv.parallel import collate, scatter
> 
> from mmseg.apis import init_segmentor
> from mmseg.datasets.pipelines import Compose
> from opencd.models import *
> 
> 
> class LoadImage:
>     """A simple pipeline to load image."""
> 
>     def __call__(self, results):
>         """Call function to load images into results.
> 
>         Args:
>             results (dict): A result dict contains the file name
>                 of the image to be read.
> 
>         Returns:
>             dict: ``results`` will be returned containing loaded image.
>         """
> 
>         results['filename'] = None
>         results['ori_filename'] = None
>         results['img'] = img
>         results['img_shape'] = img[0].shape
>         results['ori_shape'] = img[0].shape
>         return results
> 
> 
> def inference_segmentor(model, imgs):
>     """Inference image(s) with the segmentor.
> 
>     Args:
>         model (nn.Module): The loaded segmentor.
>         imgs (str/ndarray or list[str/ndarray]): Either image files or loaded
>             images.
> 
>     Returns:
>         (list[Tensor]): The segmentation result.
>     """
>     cfg = model.cfg
>     device = next(model.parameters()).device  # model device
>     # build the data pipeline
>     test_pipeline = [LoadImage()] + cfg.data.test.pipeline[1:]
>     test_pipeline = Compose(test_pipeline)
>     # prepare data
>     data = []
>     imgs = imgs if isinstance(imgs[0], list) else [imgs]
>     for img in imgs:
>         img_data = dict(img=img)
>         img_data = test_pipeline(img_data)
>         data.append(img_data)
>     data = collate(data, samples_per_gpu=len(imgs))
>     if next(model.parameters()).is_cuda:
>         # scatter to specified GPU
>         data = scatter(data, [device])[0]
>     else:
>         data['img_metas'] = [i.data[0] for i in data['img_metas']]
> 
>     # forward the model
>     with torch.no_grad():
>         result = model(return_loss=False, rescale=True, **data)
>     return result
> 
> 
> config_file = 'configs/changer/changer_ex_r18_512x512_40k_levircd.py'
> checkpoint_file = 'weights/ChangerEx_r18-512x512_40k_levircd_20221223_120511.pth'
> 
> # build the model from a config file and a checkpoint file
> model = init_segmentor(config_file, checkpoint_file, device='cuda:0')
> 
> # test a single image and show the results
> img1 = mmcv.imread('data/LEVIR-CD/test/A/test_1.png')
> img2 = mmcv.imread('data/LEVIR-CD/test/B/test_1.png')
> img = [img1, img2]
> 
> result = inference_segmentor(model, img)
> ```

Thanks for your replying!
I have already completed the `api` by myself, you can close this issue~.

**Comment by cch-meiple** [comment]
> > Sorry for the delay in replying to you, you can try the following code.
> > ```
> > import mmcv
> > import torch
> > from mmcv.parallel import collate, scatter
> > 
> > from mmseg.apis import init_segmentor
> > from mmseg.datasets.pipelines import Compose
> > from opencd.models import *
> > 
> > 
> > class LoadImage:
> >     """A simple pipeline to load image."""
> > 
> >     def __call__(self, results):
> >         """Call function to load images into results.
> > 
> >         Args:
> >             results (dict): A result dict contains the file name
> >                 of the image to be read.
> > 
> >         Returns:
> >             dict: ``results`` will be returned containing loaded image.
> >         """
> > 
> >         results['filename'] = None
> >         results['ori_filename'] = None
> >         results['img'] = img
> >         results['img_shape'] = img[0].shape
> >         results['ori_shape'] = img[0].shape
> >         return results
> > 
> > 
> > def inference_segmentor(model, imgs):
> >     """Inference image(s) with the segmentor.
> > 
> >     Args:
> >         model (nn.Module): The loaded segmentor.
> >         imgs (str/ndarray or list[str/ndarray]): Either image files or loaded
> >             images.
> > 
> >     Returns:
> >         (list[Tensor]): The segmentation result.
> >     """
> >     cfg = model.cfg
> >     device = next(model.parameters()).device  # model device
> >     # build the data pipeline
> >     test_pipeline = [LoadImage()] + cfg.data.test.pipeline[1:]
> >     test_pipeline = Compose(test_pipeline)
> >     # prepare data
> >     data = []
> >     imgs = imgs if isinstance(imgs[0], list) else [imgs]
> >     for img in imgs:
> >         img_data = dict(img=img)
> >         img_data = test_pipeline(img_data)
> >         data.append(img_data)
> >     data = collate(data, samples_per_gpu=len(imgs))
> >     if next(model.parameters()).is_cuda:
> >         # scatter to specified GPU
> >         data = scatter(data, [device])[0]
> >     else:
> >         data['img_metas'] = [i.data[0] for i in data['img_metas']]
> > 
> >     # forward the model
> >     with torch.no_grad():
> >         result = model(return_loss=False, rescale=True, **data)
> >     return result
> > 
> > 
> > config_file = 'configs/changer/changer_ex_r18_512x512_40k_levircd.py'
> > checkpoint_file = 'weights/ChangerEx_r18-512x512_40k_levircd_20221223_120511.pth'
> > 
> > # build the model from a config file and a checkpoint file
> > model = init_segmentor(config_file, checkpoint_file, device='cuda:0')
> > 
> > # test a single image and show the results
> > img1 = mmcv.imread('data/LEVIR-CD/test/A/test_1.png')
> > img2 = mmcv.imread('data/LEVIR-CD/test/B/test_1.png')
> > img = [img1, img2]
> > 
> > result = inference_segmentor(model, img)
> > ```
> 
> Thanks for your replying! I have already completed the `api` by myself, you can close this issue~.

The example code provided above uses an outdated function, so it is difficult to use it as is. Can you share the API you implemented?

**Comment by likyoo** [comment]
Hi~, Open-CD supports inference api now 😃 ! see [here](https://github.com/likyoo/open-cd/blob/main/docs/inference.md)
