### ISSUE TITLE
关于输出结果的问题

### ISSUE THREAD

**Issue by cheng-J-GITHUB** [likyoo/open-cd#89]
我在使用opencd预测结果时，输出的图片中出现了一个方框和一个unchanged字样，请问如何去掉这个方框和unchanged字样？
![00000](https://github.com/likyoo/open-cd/assets/84110272/635576dd-edc7-4f8a-bdc4-60c12fe320ba)

**Comment by likyoo** [comment]
该问题已修复，请拉取最新版本的opencd

**Comment by cheng-J-GITHUB** [comment]
好的，非常感谢
