### ISSUE TITLE
assert pred.size() == target.size() and target.numel() > 0

### ISSUE THREAD

**Issue by BennyKuya** [likyoo/open-cd#9]
When I used the data set LEVIR-CD to train the STANet network, the following error occurred---**assert pred.size() == target.size() and target.numel() > 0.**  The preliminary analysis was caused by the inconsistency of the dimensions of pred and target. The debugging found that the dimension of **pred** is torch. Size ([8, 256, 256, 256]), while the dimension of **target** is torch. Size ([8, 256, 256]). How do I need to modify the code? Thank you for your guidance and look forward to your reply。。
![image](https://user-images.githubusercontent.com/53774294/222320401-a227e1d2-4087-4bfc-8a4a-47bd1838dd61.png)

**Comment by likyoo** [comment]
[This](https://github.com/likyoo/open-cd/blob/main/opencd/models/decode_heads/sta_head.py#L341) may be helpful for you.
