### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by derowtosky** [likyoo/open-cd#97]
i just want to use the model and not train it, how can i just use the model to do some inference? such as using BIT on CDD dataset.

**Comment by ABCnutter** [comment]
If you haven't trained, you probably don't have the model weights file as well as the config file, which are needed for the inference process, so please get them first.
After obtaining these two files, if your requirement is inference for small scale images (e.g. 256×256), you can utilize opencd/tools/test.py for inference. If you need to reason about large scale images (e.g. 10000×10000), you can try to crop it to a small image (e.g. 256×256) for reasoning and then stitching, here is the reference you may need (welcome to my blog): https://blog.csdn.net/qq_43456016/article/details /136689626?spm=1001.2014.3001.5501.

Translated with DeepL.com (free version)

**Comment by ABCnutter** [comment]
If you haven't trained, you probably don't have the model weights file as well as the config file, which are needed for the inference process, so please get them first.
After obtaining these two files, if your requirement is inference for small scale images (e.g. 256×256), you can utilize opencd/tools/test.py for inference. If you need to reason about large scale images (e.g. 10000×10000), you can try to crop it to a small image (e.g. 256×256) for reasoning and then stitching, here is the reference you may need (welcome to my blog): https://blog.csdn.net/qq_43456016/article/details /136689626?spm=1001.2014.3001.5501.

**Comment by ABCnutter** [comment]
If you don't have the training, you may not have the model weight and config files, which are necessary for the inference process. Please obtain these two files first.

Once you have obtained these files, if your requirement is for inference on small-scale images (e.g., 256×256), you can utilize opencd/tools/test.py for inference. If you need to infer on large-scale images (e.g., 10000×10000), you can try cropping them into small patches (e.g., 256×256) for inference and then stitching them together. Here is a reference you might find helpful (feel free to check out my blog): https://blog.csdn.net/qq_43456016/article/details/136689626?spm=1001.2014.3001.5501.

**Comment by derowtosky** [comment]
> If you don't have the training, you may not have the model weight and config files, which are necessary for the inference process. Please obtain these two files first.
> 
> Once you have obtained these files, if your requirement is for inference on small-scale images (e.g., 256×256), you can utilize opencd/tools/test.py for inference. If you need to infer on large-scale images (e.g., 10000×10000), you can try cropping them into small patches (e.g., 256×256) for inference and then stitching them together. Here is a reference you might find helpful (feel free to check out my blog): https://blog.csdn.net/qq_43456016/article/details/136689626?spm=1001.2014.3001.5501.

thanks for your reply, where can i change the GPU id cause i have multi GPUS，i do not see any code about cuda.device

**Comment by ABCnutter** [comment]
> > If you don't have the training, you may not have the model weight and config files, which are necessary for the inference process. Please obtain these two files first.
> > Once you have obtained these files, if your requirement is for inference on small-scale images (e.g., 256×256), you can utilize opencd/tools/test.py for inference. If you need to infer on large-scale images (e.g., 10000×10000), you can try cropping them into small patches (e.g., 256×256) for inference and then stitching them together. Here is a reference you might find helpful (feel free to check out my blog): https://blog.csdn.net/qq_43456016/article/details/136689626?spm=1001.2014.3001.5501.
> 
> thanks for your reply, where can i change the GPU id cause i have multi GPUS，i do not see any code about cuda.device

You can refer to the official documentation of mmsegmentation, as it is interoperable with OpenCD (https://mmsegmentation.readthedocs.io/zh-cn/latest/user_guides/4_train_test.html). You may consider the following command line for reference:
sh tools/dist_test.sh ${config_file} ${checkpoint_file} ${num_gpus} [optional_args]

**Comment by ABCnutter** [comment]
![image](https://github.com/likyoo/open-cd/assets/91233657/3da2e113-fe70-4efb-af3e-2729c282dc13)

The test.py file contains parameters for selecting the GPU ID.
